/*
 * NTC_THERMISTOR.c
 *
 *  Created on: Nov 5, 2022
 *      Author: hp
 */

#include <math.h>
#include "math.h"
#include "NTC_THERMISTOR.h"




NTC_THERMISTOR_ID NTC_THERMISTOR_INIT(GPIO_ID* THERMISTOR_PORT,u8 THERMISTOR_PIN,u32 B_value,u32 INIT_TEMP_K,u32 INIT_NTC_RES,u32 Series_RES_VALUE)
{

	GPIO_void_PIN_MODE(THERMISTOR_PORT, THERMISTOR_PIN, GPIO_ANALOGINPUT);
	NTC_THERMISTOR_ID NTC_THERMISTOR = {THERMISTOR_PORT,THERMISTOR_PIN,B_value,INIT_TEMP_K,INIT_NTC_RES,Series_RES_VALUE};

	return NTC_THERMISTOR;

}


u32 NTC_THERMISTOR_u32_GET_TEMP(NTC_THERMISTOR_ID* NTC_THERMISTOR)
{
	u32 l_ADC_READ = 0;
	f32 l_voltge_read = 0;
	u32 R_NTC = 0;
	u32 TEMP_K = 0;

	if(NTC_THERMISTOR->THERMISTOR_PORT == GPIOA_REGS)
		ADC_u32_ANALOG_REGULAR_SingleRead_NON_BLOCKING(NTC_THERMISTOR->THERMISTOR_PIN,&l_ADC_READ);
	else
		ADC_u32_ANALOG_REGULAR_SingleRead_NON_BLOCKING(NTC_THERMISTOR->THERMISTOR_PIN+7,&l_ADC_READ);

	// x -----> 3.3
	// 0 -----> 4096
	l_voltge_read = l_ADC_READ*(NTC_VCC/4096);

	R_NTC = l_voltge_read/(NTC_VCC-l_voltge_read)*NTC_THERMISTOR->Series_RES_VALUE;

	f32 log_data = log(R_NTC)-log(NTC_THERMISTOR->INIT_NTC_RES);

	TEMP_K = (NTC_THERMISTOR->B_value*NTC_THERMISTOR->INIT_TEMP_K)/(NTC_THERMISTOR->INIT_TEMP_K*log_data+NTC_THERMISTOR->B_value);

	//return (TEMP_K - 273);
	return (u32)R_NTC;
}




/*
 *
 *
 *
 * 	RCC_void_ENABLE_PERCLK(RCC_ADC1);
	FPU_void_ENABLE();
	ADC_CHANNEL_ID ADC_CHANNELS[1] = {ADC_IN7};
	ADC_void_INIT(ADC_CHANNELS, 1);
	GPIO_ID* THERMISTOR_PORT = GPIOA_REGS;
	u8 THERMISTOR_PIN = 7;
	NTC_THERMISTOR_ID NTC_THERMISTOR = NTC_THERMISTOR_INIT(THERMISTOR_PORT, THERMISTOR_PIN, 3950, 298, 100000, 100000);
 *
 *
 *
 */
