#ifndef GPIO_PRIVATE_H
#define GPIO_PRIVATE_H

#include "LIB/STM_CONFIG.h"
#include "LIB/BIT_MATH.h"
#include "LIB/STD_TYPES.h"



typedef enum {

	GPIO_LOW_VALUE,
	GPIO_HIGH_VALUE,

}
GPIO_VALUE_ID ;

#define GPIO_NO_PULLUPDOWN 0
#define GPIO_PULLUP 1
#define GPIO_PULLDOWN 2

typedef enum {

	GPIO_LOW_SPEED,
	GPIO_MEDIUM_SPEED,
	GPIO_HIGH_SPEED,
	GPIO_VERYHIGH_SPEED,

}
GPIO_SPEED_ID ;


typedef enum {

	GPIO_INPUT,
	GPIO_INPUT_PULLUP,
	GPIO_INPUT_PULLDOWN,

	GPIO_ANALOGINPUT,

	GPIO_OUTPUT_PUSHPULL,
	GPIO_OUTPUT_PUSHPULLUP,
	GPIO_OUTPUT_PUSHPULLDOWN,

	GPIO_OUTPUT_OPENDRAIN,
	GPIO_OUTPUT_OPENDRAINUP,
	GPIO_OUTPUT_OPENDRAINDOWN,

	GPIO_AF_PUSHPULL,
	GPIO_AF_PUSHPULLUP,
	GPIO_AF_PUSHPULLDOWN,

	GPIO_AF_OPENDRAIN,
	GPIO_AF_OPENDRAINUP,
	GPIO_AF_OPENDRAINDOWN,



			}
GPIO_STATE_ID;


typedef enum {

	GPIO_AF_SYSTEM  = 0,
	GPIO_AF_TIM1 = 1,GPIO_AF_TIM2 = 1,
	GPIO_AF_TIM3 = 2,GPIO_AF_TIM4 = 2,GPIO_AF_TIM5 = 2,
	GPIO_AF_TIM9 = 3,GPIO_AF_TIM10 = 3,GPIO_AF_TIM11 = 3,
	GPIO_AF_I2C1 = 4,GPIO_AF_I2C2 = 4,GPIO_AF_I2C3 = 4,
	GPIO_AF_SPI1 = 5,GPIO_AF_SPI2 = 5,GPIO_AF_SPI4 = 5,
	GPIO_AF_SPI3 = 6 ,
	GPIO_AF_USART1 = 7,GPIO_AF_USART2 = 7,
	GPIO_AF_USART6 = 8,
	GPIO_AF_I2C_2 = 9,GPIO_AF_I2C_3 = 9,
	GPIO_AF_OTG_FS = 10,
	//
	GPIO_AF_SDIO = 11,
	//
	//
	GPIO_AF_EVENTOUT = 12,

}GPIO_AF_TYPE_ID;




typedef struct {

	u32 GPIO_MODER;
	u32 GPIO_OTYPER;
	u32 GPIO_OSPEEDR;
	u32 GPIO_PUPDR;
	u32 GPIO_IDR;
	u32 GPIO_ODR;
	u32 GPIO_BSRR;
	u32 GPIO_LCKR;
	u32 GPIOs_AFRL;
	u32 GPIOs_AFRH;

}
 GPIO_ID;

#define GPIOA_REGS (( GPIO_ID*) 0x40020000)
#define GPIOB_REGS (( GPIO_ID*) 0x40020400)
#define GPIOC_REGS (( GPIO_ID*) 0x40020800)
#define GPIOD_REGS (( GPIO_ID*) 0x40020C00)
#define GPIOE_REGS (( GPIO_ID*) 0x40021000)
#define GPIOH_REGS (( GPIO_ID*) 0x40021C00)




#endif
