/*
 * SPI_interface.h
 *
 *  Created on: Oct 13, 2022
 *      Author: hp
 */

#ifndef MCAL_SPI_SPI_INTERFACE_H_
#define MCAL_SPI_SPI_INTERFACE_H_


#include "SPI_private.h"

void SPI_INIT(SPI_PER SPI_PER_NUMER,
		SPI_MASTER_SLAVE_MODE_ID SPI_MASTER_SLAVE_MODE,
		SPI_MODE_ID SPI_MODE,
		SPI_BAUD_RATE_FACTOR_ID SPI_FACTOR,
		SPI_FRAME_SIZE_ID SPI_FRAME_SIZE,
		SPI_Frame_format_ID Frame_format);

void SPI_void_SETMODE(SPI_PER SPI_PER_NUMER,SPI_MODE_ID SPI_MODE);

void SPI_void_SETBAUDRATE(SPI_PER SPI_PER_NUMER,SPI_BAUD_RATE_FACTOR_ID SPI_FACTOR);
u8 SPI_void_GETBAUDRATE(SPI_PER SPI_PER_NUMER);


void SPI_void_TRANSMIT_BYTE(SPI_PER SPI_PER_NUMER,u16 DATA);

u16 SPI_u16_RECEIVE_BYTE(SPI_PER SPI_PER_NUMER);

void SPI_void_TRANSMIT_STRING(SPI_PER SPI_PER_NUMER,u8* DATA);

u16 SPI_u16_RECEIVE_BYTE_TX_CONTROL(SPI_PER SPI_PER_NUMER,u8 VALUE_ON_THE_TX);

#endif /* MCAL_SPI_SPI_INTERFACE_H_ */
