#ifndef STM_CONFIG_H
#define STM_CONFIG_H

#define HSE_CLOCK_SOURCE 12500000
#define HSI_CLOCK_SOURCE 16000000




#define MAIN_CLOCK_SOURCE HSE_CLOCK_SOURCE


#define AHB2_CLOCK_SOURCE HSE_CLOCK_SOURCE

#define AHB1_CLOCK_SOURCE HSE_CLOCK_SOURCE

#define APB1_CLOCK_SOURCE HSE_CLOCK_SOURCE

#define APB2_CLOCK_SOURCE HSE_CLOCK_SOURCE


#endif
