/*
 * SD_CARD.c
 *
 *  Created on: Nov 18, 2022
 *      Author: hp
 */
#include "SD_CARD_INFO.h"
#include "SD_CARD.h"
//
//	RCC_void_ENABLE_PERCLK(RCC_SPI)
// 	GPIO_void_PIN_MODE(GPIO, PIN, GPIO_STATE)
//	GPIO_void_AF_MODE(GPIO, PIN, GPIO_AF_TYPE)
//	SPI_INIT(SPI, SPI_MASTER, SPI_MODE0, SPI_BAUD_RATE_FACTOR_16, SPI_FRAME_SIZE_8, SPI_MSBF);
//

void SD_CARD_PUSH_ERROR(SD_CARD_ID* SD_CARD,u8 ERROR)
{

	SD_CARD->HW_ERROR[SD_CARD->HW_ERROR_COUNT] = ERROR;
	SD_CARD->HW_ERROR_COUNT++;
	if(SD_CARD->HW_ERROR_COUNT == SD_CARD_ERROR_LOG_ARRAY_SIZE)
	{
		SD_CARD->HW_ERROR_COUNT = 0;
	}


}


void SD_CARD_void_RECEIVE_DATA(SD_CARD_ID* SD_CARD,u8* BUFFER,u32 DATA_size)
{

	for (int i = 0; i<DATA_size;i++)
	{
		BUFFER[i] = SD_CARD_u8_SPI_RECEIVE(SD_CARD);
	}

}
void SD_CARD_ENABLE_CS(SD_CARD_ID* SD_CARD)
{
	GPIO_void_PIN_WRITE(SD_CARD->SD_CARD_CS_PORT, SD_CARD->SD_CARD_CS_PIN, GPIO_LOW_VALUE);

}

void SD_CARD_DISABLE_CS(SD_CARD_ID* SD_CARD)
{
	GPIO_void_PIN_WRITE(SD_CARD->SD_CARD_CS_PORT, SD_CARD->SD_CARD_CS_PIN, GPIO_HIGH_VALUE);

}

void SD_CARD_void_SPI_SEND(SD_CARD_ID* SD_CARD,u8 DATA)
{
	SPI_void_TRANSMIT_BYTE(SD_CARD->SD_CARD_SPI, DATA);

}

u8 SD_CARD_u8_SPI_RECEIVE(SD_CARD_ID* SD_CARD)
{
	u8 DATA = 0xFF;
	DATA = SPI_u16_RECEIVE_BYTE_TX_CONTROL(SD_CARD->SD_CARD_SPI,DATA);
	return DATA;
}


u8 SD_CARD_u8_RES_WAIT(SD_CARD_ID* SD_CARD,u32 TIME_OUT)
{
	u8 RES = 0xFF;
	u32 wait_time = 0;
	while( RES != 0xFE && GET_BIT(RES,7)!= 0 && wait_time != TIME_OUT)
	{
		RES = SD_CARD_u8_SPI_RECEIVE(SD_CARD);
		wait_time++;
	}
	if(TIME_OUT == wait_time)
	{
		SD_CARD_PUSH_ERROR( SD_CARD,R1_WAIT_ERROR);
	}
	return RES;
	//error if the return 0xFF
	}

SD_CARD_ID SD_CARD_INIT(
		SPI_PER SPI_PER_NUMER,
		GPIO_ID** SD_CARD_PORTS,u8* SD_CARD_PINS)
{
	u8 RES1 = 0xFF;
	u8 RES7 [10] ;
	Delay_ms(10);

	SPI_ID* SPI_data= (SPI_ID*)(SPI_PER_NUMER);
	u32 SPI_PREVIOUS_INFO = (SPI_data->SPI_CR1);



	for(int i = 0;i<2;i++)
	{
		GPIO_void_AF_MODE(SD_CARD_PORTS[i], SD_CARD_PINS[i], GPIO_AF_SPI1);
		GPIO_void_PIN_MODE(SD_CARD_PORTS[i],SD_CARD_PINS[i], GPIO_AF_PUSHPULLUP); // must pulled high

	}
	GPIO_void_AF_MODE(SD_CARD_PORTS[SD_CARD_SCK], SD_CARD_PINS[SD_CARD_SCK], GPIO_AF_SPI1);
	GPIO_void_PIN_MODE(SD_CARD_PORTS[SD_CARD_SCK],SD_CARD_PINS[SD_CARD_SCK], GPIO_AF_PUSHPULL);


	GPIO_void_PIN_MODE(SD_CARD_PORTS[SD_CARD_CS],SD_CARD_PINS[SD_CARD_CS], GPIO_OUTPUT_PUSHPULLDOWN);
	SPI_data->SPI_CR1 = SPI_PREVIOUS_INFO;

	SD_CARD_ID SD_CARD = { SPI_PER_NUMER,
			SD_CARD_PORTS[SD_CARD_MOSI],SD_CARD_PINS[SD_CARD_MOSI],
			SD_CARD_PORTS[SD_CARD_MISO],SD_CARD_PINS[SD_CARD_MISO],
			SD_CARD_PORTS[SD_CARD_SCK],SD_CARD_PINS[SD_CARD_SCK],
			SD_CARD_PORTS[SD_CARD_CS],SD_CARD_PINS[SD_CARD_CS],
			{0},
			0,
			SD_CARD_VER2_BYTE_ADRESS,
	};
	SD_CARD_u8_RES_WAIT(&SD_CARD, 200);
	SD_CARD_DISABLE_CS(&SD_CARD);
	for(u8 j = 0;j<3;j++)
		for(u8 i = 0;i<10;i++ )
		{
			SD_CARD_void_SPI_SEND(&SD_CARD, 0xFF);
		}

	Delay_ms(100);
	SD_CARD_ENABLE_CS(&SD_CARD);
	SD_CARD_u8_RES_WAIT(&SD_CARD, 200);

	SD_CARD_void_SEND_COMMAND(&SD_CARD, CMD0, 0x00);
	RES1 = SD_CARD_u8_RES_WAIT(&SD_CARD,200);
	if (RES1 == R1_WAIT_ERROR)
	{
		SD_CARD_PUSH_ERROR(&SD_CARD, R1_WAIT_ERROR);
		return SD_CARD;
	}

	SD_CARD_void_SEND_COMMAND(&SD_CARD, CMD8, 0x000001AA);
	RES1 = SD_CARD_u8_RES_WAIT(&SD_CARD,200);

	if(RES1 == R1_WAIT_ERROR)
	{
		SD_CARD_PUSH_ERROR(&SD_CARD, R1_WAIT_ERROR);
		return SD_CARD;
	}
//	for(int i = 0;i<4;i++)
//	{
//		RES1 = SD_CARD_u8_RES_WAIT(&SD_CARD,200);
//		RES7 |= (RES1<<(i*8));
//	}
	SD_CARD_void_RECEIVE_DATA(&SD_CARD, RES7, 10);

	if(RES7[3] != 0xaa)
	{
		SD_CARD_PUSH_ERROR(&SD_CARD,  R7_ERROR);
		//return SD_CARD;
	}

	SD_CARD_void_SEND_COMMAND(&SD_CARD, CMD55, 0x00);
	RES1 = SD_CARD_u8_RES_WAIT(&SD_CARD,200);

	if(SD_CARD.HW_ERROR[SD_CARD.HW_ERROR_COUNT] == R1_WAIT_ERROR)
	{
		SD_CARD_void_SEND_COMMAND(&SD_CARD, ACMD41, 0x00000000);
		RES1 = SD_CARD_u8_RES_WAIT(&SD_CARD,200);
		if(RES1 == 0x00)
		{
			SD_CARD.SD_CARD_VERSION = SD_CARD_VER1;
			return SD_CARD;
		}
		if(RES1 == R1_WAIT_ERROR)
		{
			return SD_CARD;

		}
	}
	else
	{
		RES1 = 0xFF;
		u8 time_out = 0;
		while((RES1 == 0xFF || RES1 == 0x01) && time_out != 100)
		{
			SD_CARD_void_SEND_COMMAND(&SD_CARD, CMD55, 0x00);
			RES1 = SD_CARD_u8_RES_WAIT(&SD_CARD,200);
			SD_CARD_void_SEND_COMMAND(&SD_CARD, ACMD41, 0x40000000);
			RES1 = SD_CARD_u8_RES_WAIT(&SD_CARD,200);
			time_out++;
		}
		if(RES1 == 0x00)
		{
			SD_CARD_void_SEND_COMMAND(&SD_CARD, CMD58, 0x00000000);
			RES1 = SD_CARD_u8_RES_WAIT(&SD_CARD,200);
			SD_CARD_void_RECEIVE_DATA(&SD_CARD, RES7, 4);

		}

		if(((RES7[0] & 0xFF) & 0x40) != 0x40 )
		{
			SD_CARD_void_SEND_COMMAND(&SD_CARD, CMD16, 0x00000200);
			SD_CARD.SD_CARD_VERSION = SD_CARD_VER2_BYTE_ADRESS;
		}
		else
		{
			SD_CARD.SD_CARD_VERSION = SD_CARD_VER2_BLOCK_ADRESS;
		}

	}
	SD_CARD_DISABLE_CS(&SD_CARD);
	SPI_data->SPI_CR1 = SPI_PREVIOUS_INFO;

	return SD_CARD;

}

void SD_CARD_void_SEND_COMMAND(SD_CARD_ID* SD_CARD,SD_CARD_COMMANDS SD_CARD_COMMAND,u32 ARGUMENT)
{
	//SD_CARD_u8_RES_WAIT(SD_CARD, 100);
	u8 fake_CRC = 0x01;
	u8 a[4] = {((ARGUMENT)>>24),((ARGUMENT)>>16),((ARGUMENT)>>8),(ARGUMENT)};

	if(CMD0 == SD_CARD_COMMAND)
		fake_CRC = 0x95;

	if(CMD8 == SD_CARD_COMMAND)
		fake_CRC = 0x87;// with argument 0x1AA

	SD_CARD_void_SPI_SEND(SD_CARD,(SD_CARD_COMMAND|0x40));
	for(int i = 0;i<4;i++)
	{

		SD_CARD_void_SPI_SEND(SD_CARD, a[i]);

	}
	SD_CARD_void_SPI_SEND(SD_CARD,fake_CRC);
}

u8 SD_CARD_u8_READ_SOME_BLOCK(SD_CARD_ID* SD_CARD,u8* BLOCK_ARRAY,u32 SIZE_OF_ARRAY,u32 START_READ,u32 END_READ);

u8 SD_CARD_u8_READ_BLOCK(SD_CARD_ID* SD_CARD,u32 LBA,u8 BLOCK_ARRAY[512])
{
	u8 R1 =0xFF;
	u8 DATA_TOKEN = 0xFF;
	u8 crc [2] = {0xFF};
	SD_CARD_ENABLE_CS(SD_CARD);
	SD_CARD_u8_RES_WAIT(SD_CARD, 200);
	SD_CARD_void_SEND_COMMAND(SD_CARD, CMD17, LBA);
	R1 = SD_CARD_u8_RES_WAIT(SD_CARD, 200);
	DATA_TOKEN = SD_CARD_u8_RES_WAIT(SD_CARD, 20000);
	if(DATA_TOKEN != 0xfe)
	{
		SD_CARD_PUSH_ERROR(SD_CARD, SD_CARD_CMD17_DATA_TOKEN_ERROR);
	}

	SD_CARD_void_RECEIVE_DATA(SD_CARD, BLOCK_ARRAY, 512);
	SD_CARD_void_RECEIVE_DATA(SD_CARD, crc,2);

	return 0;
}

