/*
 * STEPPER_DRIVER.c
 *
 *  Created on: Sep 18, 2022
 *      Author: hp
 */
#include "STEPPER_DRIVER.h"


STEPPER_ID STEPPER_INIT(GPIO_ID** STEPPER_PORTS,u8* STEPPER_PINS)
{

	for(int i = 0;i < 2;i++)
	{
		GPIO_void_PIN_MODE(STEPPER_PORTS[i], STEPPER_PINS[i], GPIO_OUTPUT_PUSHPULLUP);
	}

	STEPPER_ID STEPPER = {STEPPER_PORTS,STEPPER_PINS,0,100};

	return STEPPER;
}


void STEPPER_void_SET_STEPSNUMBER(STEPPER_ID* STEPPER,u32 steps_number)
{
	STEPPER->STEPPER_STEPS = steps_number;
}

void STEPPER_void_SET_SPEED(STEPPER_ID* STEPPER,u32 speed)
{
	STEPPER->STEPPER_DELAY_ms = speed;
}

void STEPPER_void_RUN_STEPS(STEPPER_ID* STEPPER,STEPPER_DIR_ID DIR)
{
	GPIO_void_PIN_WRITE(STEPPER->STEPPER_PORTS[1], STEPPER->STEPPER_PINS[1], DIR);

	for(int i = 0 ; i < STEPPER->STEPPER_STEPS;i++)
	{
		GPIO_void_PIN_WRITE(STEPPER->STEPPER_PORTS[0], STEPPER->STEPPER_PINS[0], GPIO_HIGH_VALUE);
		Delay_ms(STEPPER->STEPPER_DELAY_ms);
		GPIO_void_PIN_WRITE(STEPPER->STEPPER_PORTS[0], STEPPER->STEPPER_PINS[0], GPIO_LOW_VALUE);
		Delay_ms(STEPPER->STEPPER_DELAY_ms);
	}

}


void STEPPER_void_RUN_ONE_STEP(STEPPER_ID* STEPPER,STEPPER_DIR_ID DIR)
{

	GPIO_void_PIN_WRITE(STEPPER->STEPPER_PORTS[1], STEPPER->STEPPER_PINS[1], DIR);

	GPIO_void_PIN_WRITE(STEPPER->STEPPER_PORTS[0], STEPPER->STEPPER_PINS[0], GPIO_HIGH_VALUE);
	Delay_ms(STEPPER->STEPPER_DELAY_ms);
	GPIO_void_PIN_WRITE(STEPPER->STEPPER_PORTS[0], STEPPER->STEPPER_PINS[0], GPIO_LOW_VALUE);


}

