/*
 * BUTTON.c
 *
 *  Created on: Sep 13, 2022
 *      Author: hp
 */

#include "BUTTON.h"


BUTTON_ID BUTTON_BUTTON_ID_INIT(GPIO_ID* BUTTON_GPIO,u8 BUTTON_PIN)
{

	GPIO_void_PIN_MODE(BUTTON_GPIO, BUTTON_PIN, GPIO_INPUT_PULLDOWN);

	BUTTON_ID BUTTON = {BUTTON_GPIO,BUTTON_PIN};

	return BUTTON;

}
u8 BUTTON_u8_GET_INPUT(BUTTON_ID* BUTTON)
{
	return GPIO_u8_PIN_READ(BUTTON->BUTTON_GPIO,BUTTON->BUTTON_PIN);

}


u8 BUTTON_u8_WAIT(BUTTON_ID* BUTTON)
{

	while(GPIO_u8_PIN_READ(BUTTON->BUTTON_GPIO,BUTTON->BUTTON_PIN) == 0);
	return 1;

}

